services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # Register migrations so the bundle is self-contained
  Zmyslny\WrapperTags\Migration\WrapperTagsSchemaMigration:
    tags:
      - { name: contao.migration, priority: 10 }

  Zmyslny\WrapperTags\Migration\WrapperTagsClassMigration:
    tags:
      - { name: contao.migration, priority: 0 }

